# Generated by Django 5.0.2 on 2024-02-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('bio', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('date_of_birth', models.DateField()),
                ('user_type', models.CharField(choices=[('user', 'User')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
