# Generated by Django 5.0.2 on 2024-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('client', 'Client')], max_length=10),
        ),
    ]
